### ISSUE TITLE
Program se nemusí vykreslovat vždy znova

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#1]
Je zbytečné překreslovat znova celé hrací pole, ono to nepříjemně bliká -> vykreslovat jen potřebné souřadnice

**Comment by sylv1ann** [comment]
Pôvodne som to mal naprogramované presne takto :) .. vykresľoval som v podstate iba zmeny ...no pri dlhšej hre kedy sa aktualizovalo viacero políčok resp ak sa aktualizovali viackrát, sa dalo ľahšie stratiť v tom čo a koľkokrát "vybuchlo" ..samozrejme skúsim to vrátiť do tej pôvodnej podoby :)

**Comment by sylv1ann** [comment]
Prepísal som procedúru na prekresľovanie celej hracej mriežky. Nie som si však istý, či viem v konzole prekresliť iba konkrétne dané políčka, ktoré sa zmenili bez toho aby som porušil štruktúru mriežky.

**Comment by fan1x** [comment]
Koukal jsem, že používáš knihovnu CRT, ta právě obsahuje všechny potřebné funkce/procedury. Mrkni sem - http://www.math.uni-leipzig.de/pool/tuts/FreePascal/units/node2.html

Co by tě mohlo zajímat je například funkce `GotoXY()`, která umí nastavit kurzor kam potřebuješ psát (http://www.math.uni-leipzig.de/pool/tuts/FreePascal/units/node2.html#SECTION00229000000000000000)

**Comment by sylv1ann** [comment]
Zmenil som vykresľovanie pri výbuchu, teraz sa naozaj mení už iba políčko ktoré má. Použil som už spomínané Goto. Predtým som sa mu skôr snažil vyvarovať kvôli upozorneniam a neobľúbenosti tejto procedúry u iných profesorov. Dúfam, že takto to je už lepšie.

**Comment by fan1x** [comment]
Super 👍 A proč je to neoblíbená procedura u jiných profesorů? :O 
Jsou dvě rozdílné věci: 
- goto (jako příkaz): slouží ke skákání v rámci kódu, používalo se to před XX lety, když ještě nebyly IF, cykly a podobně (lze najít v ASM), dneska to ještě některé nízkoúrovňové jazyky mají, více např zde: https://en.wikipedia.org/wiki/Goto, opravdu bychom se ho měli snažit v dnešní době vyvarovat
- gotoXY() má s tím příkazem společné pouze jméno :)
