### ISSUE TITLE
Pojmenovat konstanty

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#2]
https://github.com/sylv1ann/Zapoctovy-program-1.-ZS-18/blob/f1c26393b88adacb0b65a7fb000ba31a5a505685/Exploding_Atoms.pas#L63

Nahradit čísla popisnými konstantami. Místo 65 použij například 'a' nebo si pojmenuj konstantu třeba 'ASCII_A'

**Comment by sylv1ann** [comment]
Dúfam, že sa mi podarilo pomenovať všetky konštanty, ktoré bolo treba.

**Comment by fan1x** [comment]
Pro ASCII_A by bylo lepší použít ještě na získání hodnoty 65 funkci -`Ord()/Chr()` (viz http://xoomer.virgilio.it/gciabu/engl/pascal/pas036.htm)  

Takže ideální je něco jako:
```
const asciiA = ord('A'); 
```
Respektive, pak už je zbytečné používat danou konstantu ;)

Jinak, pojmenovávat chce rozumně, nemá smysl pojmenovávat konstantu 0 jako "nula" (https://github.com/sylv1ann/Zapoctovy-program-1.-ZS-18/blob/a57bd435231243df09aefbbe20f0618e20112291/zapoctovy_program_Viktor_Bujko_1rocnik_ZS_18_19.pas#L40)

**Comment by sylv1ann** [comment]
Zmazané konštanty 'nula' a 'jedna', zmena priradenej hodnoty ku konštantám asciiA a asciima

**Comment by fan1x** [comment]
Samozřejmě se předpokládá, že to uděláš i na ostatních místech se stejným problémem, ne pouze na těch, co jsem napsal 😄

**Comment by sylv1ann** [comment]
Neviem, či som správne pochopil, na čo presne si narážal. Upravil som teda hodnoty priradzované k ostatným konštantám, aj keď neviem, či to takto nie je až príliš zložité a menej prehľadné.

**Comment by fan1x** [comment]
No... 😄 Teď jsi to udělal opravdu zbytečně složité. https://github.com/sylv1ann/Zapoctovy-program-1.-ZS-18/blob/6314361389c00049e24b10b7f2b260f3509c2766/zapoctovy_program_Viktor_Bujko_1rocnik_ZS_18_19.pas#L40
Jde to i jednoduššeji... Proč voláš `ord(char(48))`? Jaký je potom výstup?

Obecně, proč používat v programu konstanty:
- jednak aby to bylo přehledné: Když v programu používáš nějakou magickou konstantu, tak většina lidí, kteří vidí kód poprvé nechápou kde se vzala (např: `48 -> ascii0`, číslo můžu mít mnoho významů ale z názvu už se dá odvodit, že to představuje asi ascii hodnotu 0)
- předchází se tím chybám: Když programuješ, tak si nemusíš pamatovat hodnotu/pokaždé ji googlit, ale víš, že jí máš uloženou jako konstantu.

Druhá věc, není nutné použít v tomto případě konstanty, úplně by stačilo, kdybys místo konstanty například názorně použil volání funkce (kód má být čitelný/jasný...) `ord/chr`

Např:
```
{ originální: Co znamenají ty čísla?? Jsou správně??? }
if (ord(vstup[i]) >= 48) and (ord(vstup[i]) <= 57) then

--> (0)

{ ok, porovnávám hodnoty s ascii hodnotami, jsou ale ty konstanty správně }
if (ord(vstup[i]) >= ascii0) and (ord(vstup[i]) <= ascii9) then

--> (1)

{ jasný, porovnávám s ascii hodnotami čísla 0 a čísla 9 }
if (ord(vstup[i]) >= ord('0')) and (ord(vstup[i]) <= ord('9')) then

--> (2) 

{ proč tam musíš používat funkci ord??? }
if (vstup[i] >= '0') and vstup[i] <= '9' then
```

Každý programátor v pascalu zná funkci `ord`, takže je úplně fajn ji použít přímo, místo konstant...

**Comment by sylv1ann** [comment]
Jasné, že sa mi nepáčilo riešenie, ktoré veci iba zbytočne skomplikovalo. ord(char(48)) vlastne len danú hodnotu 48 iba zaobalilo, keďže najprv by ju char zmenil na znak 0 čo by potom ord premenil späť na 48.

 Myslím, že teraz som už rozumel správne. Išlo o to, že som stále rozmýšľal ako správne vyjadriť/pomenovať konštanty, keďže to bola hlavná téma tohto issue. Z predošlých správ mi to totiž vyznelo tak, že dané riešenie je len jedným z možných a že som to takto nemusel opravovať. Každopádne, teraz by to už malo byť správne tak, ako si mi to navrhol.
