### ISSUE TITLE
Proč je velikost omezená na 15x15?

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#3]

**Comment by sylv1ann** [comment]
Veľkosť je takto obmedzená, pretože ide o konzolovú aplikáciu, v ktorej som nevedel dynamicky upraviť jej veľkosť v závislosti na vstupe, a teda pri vyšších hodnotách sa napríklad mohlo stať, že sa už niektoré políčka nezarovnali pri vykreslení pekne.

**Comment by fan1x** [comment]
To nevadí, kdyžtak si uživatel může zvětšit okno :) Představoval bych si ještě tedy přidat možnost libovolného množství uživatelů a libovolnou velikost (není důvod pro to, to zbytečně omezovat ne?)

To, že to může mít **libovolnou** velikost ti naznačuje, že bych chtěl, abys to udělal pomocí dynamicky alokovaného pole ;)

**Comment by sylv1ann** [comment]
Zrušenie obmedzenia veľkosti poľa ako aj počtu hráčov. Program chybu vypíše len v prípade, že je na dané pole veľmi veľa hráčov, a teda aspoň jeden z nich by nemohol mať ani jedno políčko. Pole sa vytvára dynamicky - až v priebehu programu, po tom čo si hráči zvolia veľkosť hracieho poľa.
