### ISSUE TITLE
Používat konzistentní pojmenovávání

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#4]
https://github.com/sylv1ann/Zapoctovy-program-1.-ZS-18/blob/f1c26393b88adacb0b65a7fb000ba31a5a505685/Exploding_Atoms.pas#L49

Jednou je to `Players`, pak `tail`,

**Comment by sylv1ann** [comment]
K tomuto problému by som sa chcel skôr spýtať, či ide o veľký problém. Dve pomenovania som vybral preto, pretože prvky v poli Players odkazujú na hlavu spojového zoznamu pre každého hráča, v ktorom sú postupne pridávané políčka, ktoré si hráč privlastní. tail však ukazuje na koniec spojového zoznamu pre každého hráča, čo využívam pri pridávaní/odoberaní daného políčka.

**Comment by fan1x** [comment]
Nejde o to, že se to jmenuje jinak, to je správně. Problém je, že jedno je s malým písmenem, druhé s velkým, o to mi jde...
Podobný problém je například u konstant:
```
const
  nula = 0;
  jedna = 1;
  asciiA = 65;
  ascii_a = 97;
  ascii0 = 48;
  ascii2 = 50;
  ascii3 = 51;
  ascii4 = 52;
  ascii9 = 57;
  prvaFarba = 9;  
```
Jednou je to s podtržítkem, potom bez podtžítka s malým písmenem, potom s velkým...

Cíl je, vyber si jeden typ pojmenovávání a toho se drž a určitě to nekombinuj (pokud k tomu nemáš dobrý důvod) :)

**Comment by sylv1ann** [comment]
Konštanty 'nula' a 'jedna' odstránené, ascii_a premenované na asciima , ostatné premenné obsahujú len malé písmená ( ak sa náhodou niekde vyskytne veľké písmeno, je to len prehliadnutím pri čítaní, avšak v Pascali, ktorý nie je case sensitive to nebráni v používaní programu ). Procedúry začínajú prvým veľkým písmenom, ostatné sú malé ( rovnako, prípadné odchýlky vznikli len prehliadnutím, čomu som sa samozrejme snažil vyhnúť ).

**Comment by fan1x** [comment]
Super, já zapomněl že je Pascal case insensitive...
