### ISSUE TITLE
Nahrát na GIT jen potřebné soubory

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#5]
Nenahárvej na git nepotřebné soubory - zkus pogooglit, pravděpodobně by to mohli být `*.exe`, `*.lps`? 
viz: https://wiki.freepascal.org/Lazarus_project_files
Uživatelksé soubory se nezáváží.

**Comment by sylv1ann** [comment]
Na odkaze, ktorý si mi poslal som našiel, ktoré súbory tam asi sú zbytočne; tie som aj vymazal.
