### ISSUE TITLE
Proč jsi vypnul některé warnings?

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#6]
https://github.com/sylv1ann/Zapoctovy-program-1.-ZS-18/blob/824fb8053e33fcaf444ccc6a3569bc9e39dfd9fb/zapoctovy_program_Viktor_Bujko_1rocnik_ZS_18_19.pas#L15

Proč jsi vypnul daný warning?

**Comment by sylv1ann** [comment]
Daný warning som vypol ešte dávno, keď som daný program písal prvýkrát. Upozorňuje ma na to, že porovnanie môže byť vždy pravdivé vzhľadom na rozsah porovnania. Porovnávam však to, či môže daná súradnica v poli existovať v momente výbuchu, aby som tam teda mohol pridať nejaký atóm.
Warning som vypol skôr zo zaujímavosti, no potom som ho už nejako neriešil.

**Comment by fan1x** [comment]
Jenže teď ti program při překladu ukazuje warnings. Program by neměl (ideálně) obsahovat žádné warnings. Warnings jsou pro tebe, překladač se tě snaží upozornit na nějakou věc/chybu. Nejsou tam jen tak pro srandu...
Proč tam máš tenhle warning? 
![error1](https://user-images.githubusercontent.com/2750870/63013188-fa43f500-be8b-11e9-951c-8547fb419cc9.png)

**Comment by sylv1ann** [comment]
Warning vyskakoval pravdepodobne kvôli zlému typu premennej, ktorú som tam mal. Chyba vyskakovala stále pri 0. Všimol som si že som tam mal unsigned integer premennú, ktorú som zmenil na signed integer. Vo vyjadrení podmienky teda chyba nebola, inak by sa nedala správne detekovať existencia niektorých políčok v poli. Myslím, že takto by to už malo byť v poriadku.

**Comment by fan1x** [comment]
Super :) On to překládač sám napovídal, říkal, že typ unsigned int má vždy hodnotu >= 0, tedy nedádá smysl to kontrolovat... Protože nic nekontrolovala 😄 
Je dobré nevypínat žádné warnings, protože ty upozorňují na chyby, které jsou v programu. 

Co se dělo v případě, že `d=0`, tedy, jaká je hodnota `c`, pokud jsou obě hodnoty `unsigned int`?
```
d:=0;
c := d - 1;
```

**Comment by sylv1ann** [comment]
No ak d = 0 a c by si malo zobrať hodnotu c = d - 1, potom by v prípade unsinged int premennej hodnota c "preskočila" naspäť na najvyššiu hodnotu daného typu. Tzn. v prípade longword ( 32bit unsigned int premennej ) by teda hodnota c v tomto prípade nebola c = -1 ale c = 2^32 - 1.

**Comment by fan1x** [comment]
To je přesně ten důvod, proč nemá cenu testovat podmínku `c - 1 > 0`, protože je to vždycky (to říká překladač)
