### ISSUE TITLE
Jak používáš GIT

### ISSUE THREAD

**Issue by fan1x** [sylv1ann/Zapoctovy-program-1.-ZS-18#7]
Koukal jsem do logů jak používáš GIT? Vypadá to, že nahráváš soubory přímo přes prohlížeč. Lepší je si nainstalovat GIT pro cmd line, pokud máš rád CMD (https://git-scm.com/), nebo pokud preferuješ GUI, tak doporučuji například TortoiseGit (https://tortoisegit.org/). 
Na prvně zmiňovaném odkazu máš i postup, jak se s GITem pracuje, doporučuji pročíst.

**Comment by sylv1ann** [comment]
Prepáč, túto otázku som si minule vôbec nevšimol, a preto som na ňu bohužiaľ ani neodpovedal. Git naozaj používam cez prehliadač, no keďže v blízkej dobe si plánujem zaobstarať na prácu nový počítač, tam by som to už riešil určite niektorým zo spôsobov, ktoré si mi navrhol.

**Comment by fan1x** [comment]
Mně je to jedno, spíš to bylo takové doporučení, protože se to budeš muset naučit tak jako tak. V praxi se s tím setkáš všude (všichni používají nějaký verzovací systém - GIT, SVN, ...). A může se ti to hodit i na tvoje domácí projekty/věci, když o něco nechceš přijít (chceš zálohovat) a vidět historii (třeba diplomku, ...).
